spring:
  application:
    name: cqrs-axon
  datasource:
    url: jdbc:h2:mem:cqrsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      default:
        mode: subscribing

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080


